project:
  type: website

website:
  title: "NGS_Pipelines"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - text: Pipelines
        menu: 
          - text: RNAseq
            href: rnaseq.html
          - text: CHIPseq
          - text: Hi-C

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

